version: "3.10"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: vanhausen/diplom-work:master #sermalenk/django-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env
  bot:
    image: vanhausen/diplom-work:master #sermalenk/django-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py runbot
    restart: always
  migrations:
    image: vanhausen/diplom-work:master #sermalenk/django-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: